version: '3.9'

services:
  mariadb:
    build: srcs/requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - my_net
    # restart: always

  nginx:
    build: srcs/requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wp:/var/www/
    networks:
      - my_net
    depends_on:
      - wordpress
    # restart: always
  
  wordpress:
    build: srcs/requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/
    networks:
      - my_net
    depends_on:
      - mariadb
    # restart: always
  

volumes:
  db:
    name: volume_db
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${HOME}/data/db
  wp:
    name: volume_wp
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${HOME}/data/db

networks:
  my_net:
    driver: bridge