version: '3.7'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - volume_db:/var/lib/mysql
    expose:
      - 3306
    networks:
      - my_net
    # restart: always

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - volume_wp:/var/www/html
    networks:
      - my_net
    depends_on:
      - wordpress
    # restart: always
  
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - volume_wp:/var/www/html
    networks:
      - my_net
    expose:
      - 9000
    depends_on:
      - mariadb
    # restart: always
  

volumes:
  volume_db:
    name: volume_db
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${HOME}/data/db
  volume_wp:
    name: volume_wp
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${HOME}/data/db

networks:
  my_net:
    driver: bridge
